language: scala
script: sbt clean coverage test
after_success: sbt coveralls
deploy:
  provider: heroku
  api_key:
    secure: TA7E7H62GO1Y7cvuGE0UEDckA7cUfnK6+9myyaNa2ogG27lyVLTYJpJtGLbww6jIIQZuWzjJi/wvI1ZAHYcNJ58Ro5EFlidkdBrThUjWysisYCLHzaKNYcAJCpY3rv4KClBoruhLtlIG4kwU6EDUJGVaJo4cHzwbatxlz4QcPPw=
  app: fabricator-web
  on:
    repo: azakordonets/fabricator-web
env:
  global:
    secure: GrXvr6LlbQZq3wWZVfluOA0NaxlQ6klSd+Dj04hlb6MK0YFFlKJY0PidT6aSQcIFYUsW1iPF1ZEoMRnAlOTtjuwukhl7axrYpyhehGU5zInM9qynfdPbosZi9rWHW5DZhxzAWU5T0nQhwHXaoSvww+mmsWgnkfphWC85xtEWrOw=
